name: Deploy To Render

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies and Run Tests
        run: |
          npm install
          npm run test-component

      - name: Deploy to Render
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"